services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    command: python manage.py runserver 0.0.0.0:3000
  web:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/frontend
