# Generated by Django 4.2.1 on 2023-05-05 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('inventory_quantity', models.IntegerField()),
                ('inventory_updated_at', models.DateTimeField(default=datetime.datetime(2023, 5, 5, 6, 54, 43, 338283, tzinfo=datetime.timezone.utc))),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
